import type { Metadata } from "next";
import { Inter, Oranienbaum, Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import FooterNav from "@/components/layout/footerNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hotel Unhas Makassar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` font-poppins w-full flex flex-col justify-center`}>
        <div className="w-full flex justify-center bg-black">
          <Header />
        </div>
        <main className="w-full">{children}</main>
        <Footer />
        <FooterNav />
      </body>
    </html>
  );
}
